cmd:
  api:
    host: ${API_HOST}
    port: ${API_PORT}
    readTimeout: ${API_READ_TIMEOUT}
    writeTimeout: ${API_WRITE_TIMEOUT}
    locale: ${API_LOCALE}

    signature:
      appKey: ${API_SIGNATURE_APP_KEY}
      appSecret: ${API_SIGNATURE_APP_SECRET}
      expires: ${API_SIGNATURE_EXPIRES}

    jwt:
      key: ${API_JWT_KEY}
      issuer: ${API_JWT_ISSUER}
      subject: ${API_JWT_SUBJECT}
      expireMinutes: ${API_JWT_EXPIRE_MINUTES}

logger:
  mode: true
  savePath: ${LOGGER_SAVE_PATH}
  maxSize: ${LOGGER_MAX_SIZE}
  maxAge: ${LOGGER_MAX_AGE}
  maxBackups: ${LOGGER_MAX_BACKUPS}
  compress: ${LOGGER_MAX_COMPRESS}

cors:
  allowOrigin: "${CORS_ALLOW_ORIGIN}"
  allowMethods: "${CORS_ALLOW_METHODS}"
  allowHeaders: "${CORS_ALLOW_HEADERS}"
  allowExposeHeaders: "${CORS_EXPOSE_HEADERS}"
  allowCredentials: ${CORS_ALLOW_CREDENTIALS}

database:
  mode: false
  default:
    driver: mysql
    host: ${DB_HOST}
    port: ${DB_PORT}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    database: ${DB_DATABASE}
    more: ?charset=utf8mb4&parseTime=False&loc=Local
    prefix:
    setMaxOpenConnection: 0
    setMaxIdleConnection: 0

redis:
  mode: false
  default:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    auth: ${REDIS_AUTH}
    db: 0
    maxRetries: 1

webhook:
  wechat_work:
    url: ${WEBHOOK_WECHAT_WORK_URL}
